#Tomcat Port
server.port=9091
#Tomcat Secure
server.secure=false
#Session Time out in Seconds
server.servlet.session.timeout=1800
#Max request parameters Count. A value of less than 0 means no limit.
tomcat.maxParameterCount=-1
#Spring Configuration to keep mysql connection alive when application idle.
spring.datasource.test-while-idle=true
spring.datasource.test-on-borrow=true
spring.datasource.validation-query=SELECT 1
spring.datasource.time-between-eviction-runs-millis=5000
spring.datasource.min-evictable-idle-time-millis=60000
#Spring Multipart File Properties
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

#Logging Settings
logging.file.name=/recap-vol/logs/phase4-scsb-ui/phase4-scsb-ui.log

#adding for monitoring
#management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.config.import=optional:configserver:

spring.main.allow-circular-references = true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.web.exposure.exclude=env

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=DEBUG


# if you use the resourceserver here:
#spring.security.oauth2.resourceserver.jwt.public-key-value=


## --- registration: nypl ---
#spring.security.oauth2.client.registration.nypl.client-id=${oauth2.client.clientid}
#spring.security.oauth2.client.registration.nypl.client-secret=${oauth2.client.clientSecret}
#spring.security.oauth2.client.registration.nypl.authorization-grant-type=nypl
##spring.security.oauth2.client.registration.nypl.redirect-uri=${security.oauth2.client.pre-established-redirect-uri}
#spring.security.oauth2.client.registration.nypl.redirect-uri=http://localhost:9091/login
#
#spring.security.oauth2.client.registration.nypl.scope=openid,profile,email
#spring.security.oauth2.client.registration.nypl.provider=nypl
#
#spring.security.oauth2.client.provider.nypl.issuer-uri=https://isso.nypl.org

#spring.security.oauth2.client.provider.nypl.authorization-uri=${security.oauth2.client.userAuthorizationUri}
#spring.security.oauth2.client.provider.nypl.token-uri=${security.oauth2.client.accessTokenUri}
#spring.security.oauth2.client.provider.nypl.user-name-attribute=sub
##spring.security.oauth2.client.registration.nypl.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

server.forward-headers-strategy=framework


